### ISSUE TITLE
eagle does not open

### ISSUE THREAD

**Issue by billball61** [adafruit/Adafruit-Circuit-Playground-PCB#1]
The board file fails to open in Eagle with this message:
line 6, column 73: This is not an EAGLE file.

**Comment by microbuilder** [comment]
You likely have an old version of Eagle that doesn't support XML files.  Please use a more recent version. This board is designed in Eagle 6.4.

**Comment by billball61** [comment]
My problem is not the version but maybe because I was using the light edition (ver 7.5) to open a larger board than it will support? Just trying to get the dimensions of the board & components to start on a case design.

**Comment by billball61** [comment]
Oops, it was still in zip. Never mind :)
